### ISSUE TITLE
Only clicking on very center of delete or archive button works

### ISSUE THREAD

**Issue by ssaxnagios** [NagiosEnterprises/nsti#18]
Only clicking on the very center of the delete or archive button works:

Recommend actions:

Change line 1031 to:

    <label type='button' class='btn btn-default btn-delete delete-selected'>

Change line 1034 to:

    <label type='button' class='btn btn-default btn-archive archive-selected'>

Change line 1046 to:

    <button type='button' class='btn btn-default btn-delete delete-selected'>

Change line 1049 to:

    <button type='button' class='btn btn-default btn-archive archive-selected'>

**Comment by lgroschen** [comment]
fixed in: dc4dd10b25bc4feb1728c23c11f648990c40e39d
